import { Box, Heading, Stack } from '@chakra-ui/react'
import AddressForm from 'Components/Address/AddressForm'
import Footer from 'Components/Cart/Footer'
import Nav from 'Components/Cart/Nav'
import Form from 'Components/signup/Form'
import Head from 'next/head'
import React from 'react'

export default function Address() {
  return (
    <div>
        <Head>
            <title>Address</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/logo.png" />
        </Head>
        <main>
            <Nav/>
            <Box bg='#F4F4F4'>
              <Stack >
                <Box >
                  <AddressForm/>
                </Box>
              </Stack>
            </Box>
            <Footer/>
        </main>
    </div>
  )
}
