import { Box, Text } from "@chakra-ui/react";
import AdminMenu from "../../Admin-Side/Admin-Menu/AdminMenu";
// import Head from "next/head";

import React from "react";

const Admin = () => {
  return (
    <>
      {/* <Head>
        <title>NutriBest | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head> */}
      <Box bg={"#181e2a"}>
        <AdminMenu />
      </Box>
    </>
  );
};

export default Admin;
