import Nav from 'Components/Cart/Nav'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { data } from 'Components/Cart/cart.data'
import { Box, Heading, HStack, Stack } from '@chakra-ui/react'
import Cards from 'Components/Cart/Cards'
export default function Cart() {
    const [session,setSession] = useState([])

    console.log(session)
    

    useEffect(()=>{
        sessionStorage.setItem("data", JSON.stringify(data))
        let ss = JSON.parse(sessionStorage.getItem("data"))
        setSession(ss)
    },[])
  return (
    <div>
        <Head>
            <title>Cart</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <Nav/>
        <Box border={'1px'} pl={'40px'} pr={'40px'} pt='10px' pb='10px'>
            <Stack direction={{base:'column',lg:'row'}}>

                <Box  boxShadow='md' p='6' rounded='md' bg='white' >
                    <Heading size='md' p='10px'>shopping Cart ({session.length},item)</Heading>
                    <Box p='10px' border={'0px'}>
                        <Cards data={session}/>
                    </Box>


                </Box>
                <Box>
                    reeeeeee
                </Box>



            </Stack>
        </Box>

      </main>
    </div>
  )
}
