import Head from "next/head";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import Carousel from "@/Components/Carousel/Carousel";
const inter = Inter({ subsets: ["latin"] });
import ProductSlider from "@/Components/ProductPageComp/ProductSlider";
import Footer1 from "@/Components/Footer/Footer1";
import Footer2 from "@/Components/Footer/Footer2";
import { useEffect, useState } from "react";
import AdvertiseMain from "@/Components/Advertise/AdvertiseMain";

export default function Home() {
  const [adsdata1, setAdsdata1] = useState([]);
  const [adsdata2, setAdsdata2] = useState([]);
  const [adsdata3, setAdsdata3] = useState([]);
  const [adsdata4, setAdsdata4] = useState([]);
  const [adsdata5, setAdsdata5] = useState([]);
  const [SliderData1, setsliderData1] = useState([]);
  const [SliderData2, setsliderData2] = useState([]);
  const [SliderData3, setsliderData3] = useState([]);
  const [SliderData4, setsliderData4] = useState([]);

  const fetchAllData = async () => {
    const res = await fetch(`http://localhost:8080/Advertise1`);
    const data = await res.json();
    setAdsdata1(data);

    const res2 = await fetch(`http://localhost:8080/Advertise2`);
    const data2 = await res2.json();
    setAdsdata2(data2);

    const res3 = await fetch(`http://localhost:8080/Advertise3`);
    const data3 = await res3.json();
    setAdsdata3(data3);

    const res4 = await fetch(`http://localhost:8080/Advertise4`);
    const data4 = await res4.json();
    setAdsdata4(data4);

    const res5 = await fetch(`http://localhost:8080/Advertise5?_limit=4`);
    const data5 = await res5.json();
    setAdsdata5(data5);

    // //Product slider data
    const resProdSlider1 = await fetch(
      `http://localhost:8080/WheyProtien?_limit=4`
    );
    const Sdata1 = await resProdSlider1.json();
    setsliderData1(Sdata1);

    const resProdSlider2 = await fetch(`http://localhost:8080/Ayurvedic`);
    const Sdata2 = await resProdSlider2.json();
    setsliderData2(Sdata2);

    const resProdSlider3 = await fetch(`http://localhost:8080/Protien-Foods`);
    const Sdata3 = await resProdSlider3.json();
    setsliderData3(Sdata3);

    const resProdSlider4 = await fetch(`http://localhost:8080/Healthy_Juice`);
    const Sdata4 = await resProdSlider4.json();
    setsliderData4(Sdata4);
  };
  useEffect(() => {
    fetchAllData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Carousel />
        <AdvertiseMain data={adsdata1} />
        <ProductSlider data={SliderData1} />
        <AdvertiseMain data={adsdata2} />
        <ProductSlider data={SliderData2} />
        <AdvertiseMain data={adsdata3} />
        <ProductSlider data={SliderData3} />
        <AdvertiseMain data={adsdata4} />
        <ProductSlider data={SliderData4} />
        <AdvertiseMain data={adsdata5} />
        {/* <LoginButton /> */}
        <Footer1 />
        <Footer2 />
      </main>
    </>
  );
}

// export async function getStaticProps() {
//   // Fetch data from external API

//   // Pass data to the page via props
//   return {
//     props: {
//       data,
//       adsdata2,
//       adsdata3,
//       adsdata4,
//       adsdata5,
//       Sliderdata1,
//       Sliderdata2,
//       Sliderdata3,
//       Sliderdata4,
//     },
//   };
// }
