import { Heading } from '@chakra-ui/react'
import Nav from 'Components/Cart/Nav'
import Head from 'next/head'
import React from 'react'

export default function Payment() {
  return (
    <div>
        <Head>
            <title>payment</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/logo.png" />
        </Head>
        <main>
            <Nav/>
            <Heading>payment page</Heading>

        </main>
    </div>
  )
}
